### PR TITLE
Implement encoder

### PR DESCRIPTION
**Pull request by z38**
This last patch adds a MC-NBFX/MC-NBFS encoder. Some remarks:
- The encoder does not make use of all `RECORD_TYPE_*`. This increases the output size a bit but does not affect compatibility (e.g. an UUID or datetime stored as text will be read correctly).
- `SoapEncoderTest` depends on `soap2.bin` which has to be manually verified to be sure regular .NET clients can still read it.¹

¹ A simple reader can be found here: https://gist.github.com/z38/0d43cdbd1129a22ef2bf

### CODE REVIEW

**Comment by casperbiering** [comment]
Great work. I tried adding a few of the decoding samples tests, but the following gave errors:

``` php
array('<!--comment-->','02 07 63 6F 6D 6D 65 6E 74'),
array('<arr>true</arr><arr>false</arr><arr>true</arr><arr>false</arr><arr>true</arr>','03 40 03 61 72 72 01 B5 05 01 00 01 00 01'),
array('<arr>13107</arr><arr>-30584</arr><arr>-8739</arr>','03 40 03 61 72 72 01 8B 03 33 33 88 88 DD DD'),
```

```
1) CasperBiering\Dotnet\Tests\BinaryXml\EncoderTest::testSamples with data set #23 ('<!--comment-->', '02 07 63 6F 6D 6D 65 6E 74')
XMLReader::read(): /dotnet-binary-xml/:1: parser error : Extra content at the end of the document

/dotnet-binary-xml/src/BinaryXml/Encoder.php:43
/dotnet-binary-xml/tests/BinaryXml/EncoderTest.php:52

2) CasperBiering\Dotnet\Tests\BinaryXml\EncoderTest::testSamples with data set #24 ('<arr>true</arr><arr>false</ar...</arr>', '03 40 03 61 72 72 01 B5 05 01... 00 01')
XMLReader::read(): /dotnet-binary-xml/:1: parser error : Extra content at the end of the document

/dotnet-binary-xml/src/BinaryXml/Encoder.php:43
/dotnet-binary-xml/tests/BinaryXml/EncoderTest.php:52

3) CasperBiering\Dotnet\Tests\BinaryXml\EncoderTest::testSamples with data set #25 ('<arr>13107</arr><arr>-30584</...</arr>', '03 40 03 61 72 72 01 8B 03 33... DD DD')
XMLReader::read(): /dotnet-binary-xml/:1: parser error : Extra content at the end of the document

/dotnet-binary-xml/src/BinaryXml/Encoder.php:43
/dotnet-binary-xml/tests/BinaryXml/EncoderTest.php:52
```

Any thoughts?

**Comment by z38** [comment]
Thank you for validating the patch. As the encoder uses `\XMLReader` to parse the document, the input has to be a [well-formed XML document](http://www.w3.org/TR/REC-xml/#sec-well-formed) which means that every input has to contain exactly one root element.

So something like `<doc /><!-- comment -->` or `<arr><a /><b /><c /></arr>` should pass. I think this will not be a problem in the regular usage of the library. However, it does complicate the unit tests a bit.

It might be good idea to wrap the XMLReader error in a `EncodingException`. What do you think?

**Comment by casperbiering** [comment]
I agree that it's not a problem for regular usage.

I've implemented your idea about wrapping XMLReader/LibXML errors in an ExcodingException, and made a few other minor changes.

**Comment by z38** [comment]
Thank you for merging!

**Pull request merged**
